### ISSUE TITLE
Action crashes when it runs: TypeError: Cannot read property 'chmod' of undefined

### ISSUE THREAD

**Issue by thomas-moulard** [vale-cli/vale-action#5]
Due to a change either in the alpine package, or in the underlying Docker image, the action is currently failing when it runs, with the following error message:

```sh
/usr/bin/docker run --name af96b41506fefc84ed4768a0e87e956b331920_222ca3 --label af96b4 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_STYLES -e INPUT_CONFIG -e INPUT_FILES -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/cross_compile/cross_compile":"/github/workspace" af96b4:1506fefc84ed4768a0e87e956b331920  "https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
https://github.com/errata-ai/Joblint/releases/latest/download/Joblint.zip
" "https://gist.githubusercontent.com/jdkato/171186055d382c6065273fe5a7eeeb61/raw/c6832996f5c77002142df70a3aa2be521fe747a7/.vale.ini" "all"
/node_modules/@actions/io/lib/io-util.js:16
_a = fs.promises, exports.chmod = _a.chmod, exports.copyFile = _a.copyFile, exports.lstat = _a.lstat, exports.mkdir = _a.mkdir, exports.readdir = _a.readdir, exports.readlink = _a.readlink, exports.rename = _a.rename, exports.rmdir = _a.rmdir, exports.stat = _a.stat, exports.symlink = _a.symlink, exports.unlink = _a.unlink;
                                     ^

TypeError: Cannot read property 'chmod' of undefined
    at Object.<anonymous> (/node_modules/@actions/io/lib/io-util.js:16:38)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/@actions/io/lib/io.js:15:16)
    at Module._compile (module.js:635:30)
```

This repository CI can catch this issue. To repro, you can either force a rebuild using the UI. On my side, I forked this repository and pushed an empty commit to get the action to run in my fork:

https://github.com/thomas-moulard/vale-action

https://github.com/thomas-moulard/vale-action/commit/ea5d6c244f79e5a731f0431793e692c52baa9b9f/checks?check_suite_id=354149836

There is no difference between my fork and errata-ai/vale-action so it should also fail in this repo.

note: I would suggest to enable a [nightly job](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule) to catch those types of regressions in the future

**Comment by jdkato** [comment]
This should be fixed now.

**Comment by thomas-moulard** [comment]
This fixed the issue, thank you!

It would be great to pin the Docker image version in the Dockerfile to avoid having updates to the base image break the action IMHO.
